name: golangci-lint
on:
  push:
    paths:
      - apps/**
      - pkg/**
      - .github/workflows/go_lint.yml
      - go.*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: make gen-go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: |
            --config .golangci.toml --max-same-issues=0 --max-issues-per-linter=0 --verbose
            $(go list -m -f '{{.Path}}/...' | grep pkg/) ./pkg/...
          install-mode: binary
